# Generated 2026-03-13 from:
# /home/caryzxy/projects/ravdess_speaker_id/train_finetune_ecapa.yaml
# yamllint disable
seed: 1986
__set_seed: !apply:speechbrain.utils.seed_everything [1986]

data_folder: /home/caryzxy/datasets/Audio_Speech_Actors_01-24
output_folder: /home/caryzxy/projects/ravdess_speaker_id/exp_ecapa_finetune
save_folder: /home/caryzxy/projects/ravdess_speaker_id/exp_ecapa_finetune/save
train_log: 
  /home/caryzxy/projects/ravdess_speaker_id/exp_ecapa_finetune/train_log.txt

train_annotation: 
  /home/caryzxy/projects/ravdess_speaker_id/ravdess_manifests/train.csv
valid_annotation: 
  /home/caryzxy/projects/ravdess_speaker_id/ravdess_manifests/valid.csv
test_annotation: 
  /home/caryzxy/projects/ravdess_speaker_id/ravdess_manifests/test.csv

pretrained_savedir: /home/caryzxy/projects/ravdess_speaker_id/pretrained_ecapa

number_of_epochs: 20
batch_size: 8
lr_start: 1.0e-4
lr_final: 1.0e-5
n_classes: 24
emb_dim: 192
classifier_hidden: 256
num_workers: 0
freeze_encoder: false

dataloader_options:
  batch_size: 8
  num_workers: 0

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: 
    /home/caryzxy/projects/ravdess_speaker_id/exp_ecapa_finetune/train_log.txt

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.classification_error
    reduction: batch

epoch_counter: &id001 !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: 20

opt_class: !name:torch.optim.Adam
  lr: 1.0e-4

lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
  initial_value: 1.0e-4
  final_value: 1.0e-5
  epoch_count: 20

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: 
    /home/caryzxy/projects/ravdess_speaker_id/exp_ecapa_finetune/save
  recoverables:
    classifier: !new:torch.nn.Identity
    counter: *id001
